// <auto-generated />
namespace AssignmentFPTBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialRun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialRun));
        
        string IMigrationMetadata.Id
        {
            get { return "202202240405525_InitialRun"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
